/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import scripts.Conexao;

/**
 *
 * @author vinic
 */
public class InserirLote extends javax.swing.JFrame {

    /**
     * Creates new form InserirLote
     */
    public InserirLote() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtSenha = new javax.swing.JTextField();
        addLote = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        addLoteBD = new javax.swing.JButton();

        jLabel1.setText("Email:");

        jLabel2.setText("Nome:");

        jLabel3.setText("Senha:");

        addLote.setText("Adicionar ao Lote");
        addLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLoteActionPerformed(evt);
            }
        });

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Email", "Nome", "Senha"
            }
        ));
        jScrollPane1.setViewportView(tabela);

        addLoteBD.setBackground(new java.awt.Color(51, 255, 51));
        addLoteBD.setForeground(new java.awt.Color(0, 0, 255));
        addLoteBD.setText("Inserir Lote no BD");
        addLoteBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLoteBDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(addLote, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(77, 77, 77)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1)
                                .addComponent(jLabel3))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                .addComponent(txtSenha)
                                .addComponent(txtNome))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(addLoteBD, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addLote)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addLoteBD)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLoteActionPerformed
        // TODO add your handling code here:
        if (txtEmail.equals(null) || txtEmail.getText().isEmpty() && txtNome.equals(null)
                || txtNome.getText().isEmpty() && txtSenha.equals(null) 
                || txtSenha.getText().isEmpty()) {
            
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
        } else {
            DefaultTableModel tModelo = (DefaultTableModel) tabela.getModel();
            Object[] dados = {txtEmail.getText(), txtNome.getText(), txtSenha.getText()};
            tModelo.addRow(dados);
        }
    }//GEN-LAST:event_addLoteActionPerformed

    private void addLoteBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLoteBDActionPerformed
        // TODO add your handling code here:
        Connection conn = null;
        PreparedStatement ps = null;
        DefaultTableModel tModel = (DefaultTableModel) tabela.getModel();
        String sql = "insert into usuario (email,nome,senha) values(?,?,?)";
        
        try {
            conn = Conexao.getConnection();
            conn.setAutoCommit(false);
            ps = conn.prepareStatement(sql);
            
            ArrayList<String> dadosTModelo = new ArrayList<>();
            for (int i = 0; i < tModel.getRowCount(); i++) {
                dadosTModelo.add(tModel.getValueAt(i, 0).toString());
                dadosTModelo.add(tModel.getValueAt(i, 1).toString());
                dadosTModelo.add(tModel.getValueAt(i, 2).toString());
                
            }
            for (int i = 0; i < dadosTModelo.size(); i++) {
                ps.setString(1, dadosTModelo.get(i));
                i++;
                ps.setString(2, dadosTModelo.get(i));
                i++;
                ps.setString(3, dadosTModelo.get(i));
                ps.executeUpdate();
            }
            JOptionPane.showMessageDialog(null, "Lote adicionado com sucesso!");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Erro! msg:" + e.getMessage());
            try {
                conn.rollback();
            } catch (SQLException ex) {
               JOptionPane.showMessageDialog(null, "Erro! msg:" + e.getMessage()); 
            }
        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, "Erro! msg:" + e.getMessage());
            try {
                conn.rollback();
            } catch (SQLException ex) {
               JOptionPane.showMessageDialog(null, "Erro! msg:" + e.getMessage()); 
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro! msg:" + e.getMessage());
            try {
                conn.rollback();
            } catch (SQLException ex) {
               JOptionPane.showMessageDialog(null, "Erro! msg:" + e.getMessage()); 
            }
        } finally {
            try {
                conn.commit();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Erro! msg:" + ex.getMessage()); 
            }
            Conexao.closeConnection(conn, ps);
            
        }
    }//GEN-LAST:event_addLoteBDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InserirLote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InserirLote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InserirLote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InserirLote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InserirLote().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addLote;
    private javax.swing.JButton addLoteBD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSenha;
    // End of variables declaration//GEN-END:variables
}
