/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author vinic
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form q3
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BarraMenu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        manterU = new javax.swing.JMenuItem();
        listarU = new javax.swing.JMenuItem();
        addLoteUsu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setBackground(new java.awt.Color(0, 0, 0));
        jMenu1.setText("Usuário");

        manterU.setBackground(new java.awt.Color(153, 153, 153));
        manterU.setText("Cadastro");
        manterU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manterUActionPerformed(evt);
            }
        });
        jMenu1.add(manterU);

        listarU.setBackground(new java.awt.Color(102, 102, 102));
        listarU.setText("Consultar");
        listarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarUActionPerformed(evt);
            }
        });
        jMenu1.add(listarU);

        addLoteUsu.setText("Adicionar Lote de Usuários");
        addLoteUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLoteUsuActionPerformed(evt);
            }
        });
        jMenu1.add(addLoteUsu);

        BarraMenu.add(jMenu1);

        setJMenuBar(BarraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarUActionPerformed
        q2 listar = new q2();
        listar.setVisible(true);
    }//GEN-LAST:event_listarUActionPerformed

    private void manterUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manterUActionPerformed
     q1 manter = new q1();
     manter.setVisible(true);
    }//GEN-LAST:event_manterUActionPerformed

    private void addLoteUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLoteUsuActionPerformed
        // TODO add your handling code here:
        InserirLote addLote = new InserirLote();
        addLote.setVisible(true);
    }//GEN-LAST:event_addLoteUsuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarraMenu;
    private javax.swing.JMenuItem addLoteUsu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem listarU;
    private javax.swing.JMenuItem manterU;
    // End of variables declaration//GEN-END:variables
}
